name: Code quality
on:
  push:
    branches:
      - main
      - stable/*
      - release/*
      - trying
      - staging
  pull_request: {}
jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          queries: +security-and-quality
      - name: Build
        run: mvn -B -T1C -DskipTests -DskipChecks install
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  go-lint:
    name: Go linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.32
          working-directory: clients/go
  java-format:
    name: Java formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn -T1C -B -D skipTests -P checkFormat,-autoFormat validate
